version: 1
disable_existing_loggers: false
formatters:
  notinsane:
    class: logging.Formatter
    style: "{"
    datefmt: "%Y-%m-%dT%H:%M:%S%z"
    format: "{asctime:s} {threadName:s} {levelname:s} {name:s}:{lineno:d} - {message:s}"
handlers:
  console:
    level: DEBUG
    class: logging.StreamHandler
    formatter: notinsane
    stream: ext://sys.stderr
root:
  handlers:
    - console
  level: DEBUG
